name: Test Aja Dulu

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TOKEN }}  # <-- ini yang nambahin env
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Run Go test/main
      run: go run ./cmd/bot
